/**
 * Measure per-field extraction ACCURACY against the synthetic gold manifest
 * (4 Sep 2026, walkthrough finding 7).
 *
 * ## Why this exists
 *
 * "Confidence up to 98%" was said out loud with no mechanical embodiment behind
 * it: the confidence-threshold seam is deliberately empty (eval-calibrated,
 * does not exist yet), and the only accuracy figures on record were research
 * numbers about CATEGORISATION (~62.5–79%, `docs/research/business-types-and-
 * accounts.md`), not a measurement of what the pinned extractor reads. A claim
 * with no way to re-take it decays into folklore — the same argument as
 * `extraction-cost.ts` beside this file, which is also this script's chassis.
 *
 * ## What it measures, and what it deliberately does not
 *
 * The REAL `BedrockExtractor` — production class, real system prompt, real
 * forced tool call, the model pinned in `chat-framework/models.ts` — against
 * the synthetic corpus in `fixtures/synthetic/`, scored per field against the
 * expected-values manifest in `docs/testing/gpt-test-document-prompts.md` §9.
 * Five fields per document: supplier, date, total, VAT, reference.
 *
 * ⚠ **The gold table describes the PROMPTS, not necessarily the PIXELS.** The
 * image fixtures were generated by an image model, which mangles digits, so a
 * mismatch on an image fixture means ONE OF: the extractor misread, or the
 * generator mis-rendered. The verdict column says which corpus class the
 * document is (`pdf` = born-digital, the pixels ARE the prompt; `image` =
 * generated, adjudicate by eye before blaming the extractor). Do not quote the
 * image-row failures as extraction errors without looking at the image.
 *
 * ⚠ **n is small.** Nine documents, forty-five field reads. This is a smoke
 * measurement that replaces an invented number with a taken one; it is not a
 * calibration corpus. Growing `evals/` a real extraction dataset is still owed
 * (its README says so in as many words).
 *
 * ## Running it
 *
 *   pnpm tsx scripts/measure/extraction-accuracy.ts
 *
 * Spends real money — nine model calls, ~10–15p total — against whatever AWS
 * credentials the environment resolves. Re-run whenever the model pin, prompt
 * or tool schema moves. The HTML fixtures must first be printed to PDF
 * (playwright `page.pdf`); the PNG fixtures are used as they are.
 */

import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { setTimeout as sleep } from 'node:timers/promises';

import { AnthropicBedrock } from '@anthropic-ai/bedrock-sdk';

import { InMemoryAiBudget } from '../../apps/api/src/common/ai-budget.js';
import { MODELS, TASKS } from '../../apps/api/src/modules/chat-framework/index.js';
import { BedrockExtractor } from '../../apps/api/src/modules/extraction/bedrock-extractor.js';
import type { ExtractedDocument } from '../../apps/api/src/modules/extraction/document-extractor.js';
import type { DocumentStore } from '../../apps/api/src/modules/ingestion-routing/index.js';

const REGION = process.env['BEDROCK_REGION'] ?? 'eu-west-2';
const FIXTURES = resolve('fixtures/synthetic');

/** The §9 expected-values manifest, transcribed. Money is integer pence. */
interface Gold {
  readonly file: string;
  readonly mimeType: 'application/pdf' | 'image/png';
  /** `pdf` rows are born-digital (pixels ARE the prompt); `image` rows were generated and may mis-render digits. */
  readonly corpus: 'pdf' | 'image';
  readonly supplier: string;
  readonly date: string;
  readonly totalPence: number;
  readonly taxPence: number;
  readonly reference: string | null;
}

const GOLD: readonly Gold[] = [
  { file: '3.1-wolseley-2026-08-05.pdf', mimeType: 'application/pdf', corpus: 'pdf', supplier: 'Wolseley', date: '2026-08-05', totalPence: 43010, taxPence: 7168, reference: 'WOL-1036' },
  { file: '3.2-bidfood-2026-08-03.png', mimeType: 'image/png', corpus: 'image', supplier: 'Bidfood', date: '2026-08-03', totalPence: 48240, taxPence: 0, reference: null },
  { file: '3.3-currys-business-2026-08-08.pdf', mimeType: 'application/pdf', corpus: 'pdf', supplier: 'Currys Business', date: '2026-08-08', totalPence: 89999, taxPence: 15000, reference: 'CB-88214' },
  { file: '3.4a-london-linen-2026-08-12.pdf', mimeType: 'application/pdf', corpus: 'pdf', supplier: 'London Linen Co', date: '2026-08-12', totalPence: 15600, taxPence: 2600, reference: 'LLC-2026-0812' },
  { file: '3.4b-london-linen-2026-08-26.pdf', mimeType: 'application/pdf', corpus: 'pdf', supplier: 'London Linen Co', date: '2026-08-26', totalPence: 15600, taxPence: 2600, reference: 'LLC-2026-0826' },
  { file: '3.5-fresh-direct-2026-08-14.png', mimeType: 'image/png', corpus: 'image', supplier: 'Fresh Direct', date: '2026-08-14', totalPence: 21750, taxPence: 0, reference: null },
  { file: '3.6-wolseley-2026-08-20.pdf', mimeType: 'application/pdf', corpus: 'pdf', supplier: 'Wolseley', date: '2026-08-20', totalPence: 8640, taxPence: 1440, reference: 'WOL-1099' },
  { file: '4-bidfood-rephoto-2026-08-03.png', mimeType: 'image/png', corpus: 'image', supplier: 'Bidfood', date: '2026-08-03', totalPence: 48240, taxPence: 0, reference: null },
  { file: '7b-wolseley-credit-note-2026-08-25.pdf', mimeType: 'application/pdf', corpus: 'pdf', supplier: 'Wolseley', date: '2026-08-25', totalPence: -4560, taxPence: -760, reference: 'CN-0455' },
];

/** Bytes from disk instead of S3 — the one stand-in in this measurement. */
function storeOf(bytes: Buffer): DocumentStore {
  return { get: () => Promise.resolve(bytes) } as unknown as DocumentStore;
}

/** Case/punctuation-tolerant supplier compare: "Wolseley UK Ltd" matches "Wolseley". */
function supplierMatches(read: string | null, gold: string): boolean {
  if (read === null) return false;
  const norm = (v: string) => v.toLowerCase().replace(/\b(ltd|limited|co|uk|plc)\b/g, '').replace(/[^a-z0-9]/g, '');
  return norm(read).includes(norm(gold)) || norm(gold).includes(norm(read));
}

/** A credit note read as a magnitude with docType CREDIT_NOTE counts as read: the sign is the type. */
function moneyMatches(read: number | null, gold: number, docType: string): boolean {
  if (read === null) return false;
  if (read === gold) return true;
  return gold < 0 && docType === 'CREDIT_NOTE' && read === Math.abs(gold);
}

function referenceMatches(read: string | null, gold: string | null): boolean {
  if (gold === null) return true; // the document carries none; anything the model offers is not scored
  if (read === null) return false;
  return read.replace(/\s/g, '').toLowerCase().includes(gold.replace(/\s/g, '').toLowerCase());
}

interface Row {
  readonly file: string;
  readonly corpus: 'pdf' | 'image';
  readonly ok: boolean;
  readonly fields: Readonly<Record<'supplier' | 'date' | 'total' | 'vat' | 'reference', boolean>> | null;
  readonly detail: string;
}

function score(gold: Gold, doc: ExtractedDocument): Row['fields'] {
  return {
    supplier: supplierMatches(doc.supplierName, gold.supplier),
    date: doc.documentDate === gold.date,
    total: moneyMatches(doc.totalPence, gold.totalPence, doc.docType),
    vat: moneyMatches(doc.taxPence, gold.taxPence, doc.docType),
    reference: referenceMatches(doc.reference, gold.reference),
  };
}

async function main(): Promise<void> {
  process.stdout.write(`\nExtraction accuracy probe — walkthrough finding 7\n`);
  process.stdout.write(`  model   ${MODELS[TASKS.extractionVisionFirst.model]}\n`);
  process.stdout.write(`  region  ${REGION}\n`);
  process.stdout.write(`  corpus  ${GOLD.length} documents · 5 fields each · gold from docs/testing/gpt-test-document-prompts.md §9\n\n`);

  const rows: Row[] = [];
  for (const gold of GOLD) {
    const bytes = readFileSync(resolve(FIXTURES, gold.file));
    const budget = new InMemoryAiBudget(1_000_000);
    const client = new AnthropicBedrock({ awsRegion: REGION, maxRetries: 1 });
    const extractor = new BedrockExtractor({
      store: storeOf(bytes),
      region: REGION,
      budget,
      client: { messages: { create: client.messages.create.bind(client.messages) } } as unknown as Pick<AnthropicBedrock, 'messages'>,
    });
    process.stdout.write(`reading ${gold.file}...\n`);
    const outcome = await extractor.extract({
      filename: gold.file,
      byteHash: 'accuracy-probe',
      s3Key: 'accuracy-probe',
      mimeType: gold.mimeType,
      practiceId: 'measure',
    });
    if (!outcome.ok) {
      rows.push({ file: gold.file, corpus: gold.corpus, ok: false, fields: null, detail: `${outcome.failure.code} ${outcome.failure.message}` });
    } else {
      const d = outcome.document;
      rows.push({
        file: gold.file,
        corpus: gold.corpus,
        ok: true,
        fields: score(gold, d),
        detail: `read supplier=${d.supplierName} date=${d.documentDate} total=${d.totalPence} vat=${d.taxPence} ref=${d.reference} type=${d.docType}`,
      });
    }
    await sleep(400);
  }

  process.stdout.write('\nfile                                       supplier date total vat ref\n');
  for (const row of rows) {
    if (row.fields === null) {
      process.stdout.write(`${row.file.padEnd(42)} FAILED — ${row.detail}\n`);
      continue;
    }
    const mark = (v: boolean) => (v ? '  ✓  ' : '  ✗  ');
    process.stdout.write(
      `${row.file.padEnd(42)}${mark(row.fields.supplier)}${mark(row.fields.date)}${mark(row.fields.total)}${mark(row.fields.vat)}${mark(row.fields.reference)}\n`,
    );
    process.stdout.write(`  ${row.detail}\n`);
  }

  const tally = (subset: readonly Row[]): string => {
    const scored = subset.filter((r) => r.fields !== null);
    const checks = scored.flatMap((r) => Object.values(r.fields ?? {}));
    const hits = checks.filter(Boolean).length;
    return `${hits}/${checks.length} fields (${checks.length === 0 ? '—' : `${((hits / checks.length) * 100).toFixed(1)}%`}) over ${scored.length} read + ${subset.length - scored.length} failed docs`;
  };
  process.stdout.write(`\nborn-digital PDFs (pixels ARE the prompt): ${tally(rows.filter((r) => r.corpus === 'pdf'))}\n`);
  process.stdout.write(`generated images (adjudicate ✗ by eye):    ${tally(rows.filter((r) => r.corpus === 'image'))}\n`);
  process.stdout.write(`whole corpus:                              ${tally(rows)}\n\n`);
  process.stdout.write('⚠ n is small, the corpus is synthetic, and image-row misses may be the image\n');
  process.stdout.write('generator rather than the extractor. This replaces an invented number with a\n');
  process.stdout.write('taken one; it is not a calibration. Nothing here justifies quoting 98%.\n\n');
}

main().catch((error: unknown) => {
  process.stderr.write(`${error instanceof Error ? error.stack : String(error)}\n`);
  process.exitCode = 1;
});
