/**
 * @neoting/contracts — the build-first API contract (Sprint-0 artefact, LAW).
 *
 * Import from a subpath, not from here, so nothing pulls in what it does not
 * need:
 *
 *   @neoting/contracts/zod     Zod schemas — apps/api boundaries, apps/web forms
 *   @neoting/contracts/model   TypeScript types for every DTO
 *   @neoting/contracts/client  TanStack Query hooks + MSW handlers — apps/web only
 *
 * This barrel carries only what both sides share: the typed error hierarchy and
 * the fetch wrapper, which have no React or MSW dependency.
 *
 * Everything under src/generated/ is generated by `pnpm generate`. Never
 * hand-edit it (R3). Fix openapi.yaml and regenerate — a hand-patched type is
 * why integration takes a week instead of two days.
 */
export { ntFetch, NtProblemError, NtTransportError } from './http-client.js';
