/**
 * @neoting/contracts — the build-first API contract (Sprint-0 artefact, LAW).
 *
 * Import from a subpath, not from here, so nothing pulls in what it does not
 * need:
 *
 *   @neoting/contracts/zod     Zod schemas — apps/api boundaries, apps/web forms
 *   @neoting/contracts/model   TypeScript types for every DTO
 *   @neoting/contracts/client  TanStack Query hooks + MSW handlers — apps/web only
 *
 * This barrel carries only what both sides share: the typed error hierarchy and
 * the fetch wrapper, which have no React or MSW dependency.
 *
 * Everything under src/generated/ is generated by `pnpm generate`. Never
 * hand-edit it (R3). Fix openapi.yaml and regenerate — a hand-patched type is
 * why integration takes a week instead of two days.
 */
export { ntFetch, NtProblemError, NtTransportError } from './http-client.js';
/**
 * The retention window (review items 61 + 67). Not a generated artefact and not
 * in `openapi.yaml` — a product policy figure that the server's purge sweep and
 * the browser's confirmation copy must state identically, and this is the one
 * package both can see. See `retention.ts` for the whole argument.
 */
export { TRASH_RETENTION_DAYS, TRASH_RETENTION_POLICY_ID } from './retention.js';
